"""WAF detection from response fingerprints.

Before (and during) active testing it pays to know whether a WAF fronts the
target: it changes the pacing envelope (rate limits, IP bans) and whether payload
evasion is worth attempting. Detection is signature-based over the server header,
cookies, body phrases, and block-status codes — the same kind of fingerprinting
recon does for edge providers, at the request layer.
"""

from __future__ import annotations

from typing import Any, Dict, List

# name -> {server: [...substrings], cookie: [...prefixes], body: [...substrings]}
WAF_SIGNATURES: Dict[str, Dict[str, List[str]]] = {
    "cloudflare": {"server": ["cloudflare"], "cookie": ["__cfduid", "__cf_bm", "cf_clearance"],
                   "body": ["attention required", "cloudflare", "cf-ray"]},
    "akamai": {"server": ["akamaighost", "akamai"], "cookie": ["ak_bmsc", "bm_sz"],
               "body": ["akamai", "reference #"]},
    "imperva_incapsula": {"server": ["incapsula"], "cookie": ["incap_ses", "visid_incap", "nlbi_"],
                          "body": ["incapsula", "_incapsula_resource"]},
    "aws_waf": {"server": ["awselb"], "cookie": ["aws-waf-token", "awsalb"],
                "body": ["request blocked", "aws waf"]},
    "f5_big_ip": {"server": ["big-ip", "bigip"], "cookie": ["bigipserver", "ts0"],
                  "body": ["the requested url was rejected", "support id"]},
    "modsecurity": {"server": ["mod_security", "modsecurity"], "cookie": [],
                    "body": ["mod_security", "this error was generated by mod_security",
                             "not acceptable"]},
    "sucuri": {"server": ["sucuri"], "cookie": ["sucuri-"],
               "body": ["sucuri", "access denied - sucuri website firewall"]},
    "ddos_guard": {"server": ["ddos-guard"], "cookie": ["__ddg"], "body": ["ddos-guard"]},
    "fortiweb": {"server": ["fortiweb"], "cookie": ["cookiesession1"],
                 "body": ["blocked by fortiweb"]},
}

# Status codes WAFs commonly use to block.
_BLOCK_STATUSES = {403, 406, 419, 429, 503}


def _lower(s: Any) -> str:
    return str(s or "").lower()


def detect(status: int, headers: Dict[str, str], body: bytes) -> List[str]:
    """Return the names of WAFs whose signature matches the response."""
    h = {k.lower(): _lower(v) for k, v in (headers or {}).items()}
    server = h.get("server", "")
    # cookie names appear across set-cookie + any cookie-ish headers
    cookie_blob = " ".join(v for k, v in h.items() if "cookie" in k)
    text = _lower(body.decode("utf-8", errors="replace") if isinstance(body, bytes) else body)
    hits: List[str] = []
    for name, sig in WAF_SIGNATURES.items():
        if (any(s in server for s in sig["server"])
                or any(c in cookie_blob for c in sig["cookie"])
                or any(b in text for b in sig["body"])):
            hits.append(name)
    return hits


def detect_from_response(resp) -> List[str]:
    """Convenience wrapper over a :class:`core.http.Response`-like object."""
    return detect(getattr(resp, "status", 0) or 0, dict(getattr(resp, "headers", {}) or {}),
                  getattr(resp, "body", b"") or b"")


def is_block(status: int) -> bool:
    return status in _BLOCK_STATUSES


__all__ = ["WAF_SIGNATURES", "detect", "detect_from_response", "is_block"]
