"""Tests for core.waf — detection + evasion mutations + CLI."""

from core.waf import detect, evasion
from core.waf.cli import main


def test_detect_cloudflare_by_server_and_cookie():
    assert "cloudflare" in detect.detect(
        403, {"Server": "cloudflare", "Set-Cookie": "__cf_bm=x"}, b"Attention Required")
    assert detect.detect(200, {"Server": "nginx"}, b"hello world") == []


def test_detect_modsecurity_by_body():
    assert "modsecurity" in detect.detect(
        406, {}, b"This error was generated by Mod_Security")


def test_detect_multiple_and_block_status():
    hits = detect.detect(403, {"Server": "cloudflare"}, b"incapsula incident")
    assert "cloudflare" in hits and "imperva_incapsula" in hits
    assert detect.is_block(403) and not detect.is_block(200)


def test_mutations_include_encodings_and_are_unique():
    variants = evasion.mutations("' UNION SELECT 1")
    assert variants[0] == "' UNION SELECT 1"          # original first
    assert any("%27" in v for v in variants)           # url-encoded
    assert any("/**/" in v for v in variants)          # comment-spaced
    assert len(variants) == len(set(variants))         # de-duplicated


def test_mutations_double_encode():
    variants = evasion.mutations("<script>")
    assert any("%253C" in v for v in variants)         # double url-encode of '<'


def test_cli_mutate_offline():
    assert main(["--mutate", "' OR 1=1"]) == 0


def test_cli_url_requires_active_and_auth(capsys):
    assert main(["--url", "https://x.test"]) == 2
    assert "active" in capsys.readouterr().err
    assert main(["--url", "https://x.test", "--active"]) == 2
    assert "authorization" in capsys.readouterr().err
